env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      -
        goos: darwin
        goarch: 386
    flags:
      - "-a"
    ldflags:
      - '-extldflags "-static"'
checksum:
  name_template: '{{.ProjectName}}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    format_overrides:
    wrap_in_directory: true
brews:
  -
    name: berty-library-test
#    github:
#      owner: moul
#      name: homebrew-moul
    commit_author:
      name: moul-bot
      email: "bot@moul.io"
    homepage: https://github.com/moul/berty-library-test
    description: "berty-library-test"
nfpms:
  -
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/moul/berty-library-test
    description: "berty-library-test"
    maintainer: "Manfred Touron <https://manfred.life>"
    license: "Apache-2.0 OR MIT"
    vendor: moul
    formats:
      - deb
      - rpm
